### ISSUE TITLE
IOS登陆提示邮箱不存在

### ISSUE THREAD

**Issue by howcooll** [PlexVPN/plex#20]
安卓和pc正常登陆使用，ios登陆提示邮箱不存在。

**Comment by PandaVPN** [comment]
您好，请通过客户端联系在线客服或者客服邮箱（iplexservice@gmail.com），以便尽快为您解决问题。

**Comment by howcooll** [comment]
在线客服没在啊。点开客服就是“稍安勿躁，客服小哥哥小姐姐正在来的途中...”

**Comment by PandaVPN** [comment]
您好，客服一直都在的，请在客户端在线联系客服留言，客服看到后会第一时间回复您的。

**Comment by PlexVPN** [comment]
您好， 请通过客户端在线联系客服或者客服邮箱（iplexservice@gmail.com），以便尽快为您解决问题。

**Comment by PandaVPN** [comment]
您好，在的，您提供一下报错截图


Best Regards,
————————————————
PandaVPN Team
