### ISSUE TITLE
2019-09-16 不能用了

### ISSUE THREAD

**Issue by wanciyang** [PlexVPN/plex#7]
在油管听得歌，下午5半左右突然不能连接了，希望尽快修复

**Comment by qiaowenchuan** [comment]
现在还不能用，希望尽快修复。

**Comment by PlexVPN** [comment]
您好，如果您所在地区线路连接后无法上网，可以连接后缀是IPLC或Relay的节点替代使用。 如中国-香港 10[APNIC][IPLC]，中国-香港 12[APNIC][IPLC]，中国-台湾 3[HiNet][IPLC]，美国-洛杉矶 2 [CN2][IPLC]...部分节点在修复，修复完毕会补偿您时长。
