### ISSUE TITLE
登录失败！

### ISSUE THREAD

**Issue by 2293310198** [PlexVPN/plex#8]
******* processError
processError "login" "" 

******* onReloginFailed
*****************relogin
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
requestTimeout QNetworkReply::NetworkError(UnknownNetworkError)
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
******* processError
processError "relogin" "" 

******* onReloginFailed
Relogin failed! 连接失败，请检查网络
很显然报错了

**Comment by 2293310198** [comment]
这应该是qt5自带的啊
再说我也装了openssl

**Comment by xuNan784328295** [comment]
2019-11-28 08:17:47 - [Debug] (cnetworkprocessor.cpp:719, void CNetWorkProcessor::requestTimeout(QNetworkReply::NetworkError)): requestTimeout QNetworkReply::NetworkError(InternalServerError)

**Comment by PlexVPN** [comment]
您好，请退出重新登录并切换其他浏览器再试试。若仍有问题，请通过客户端在线反馈联系客服发送具体的报错截图。
